### ISSUE TITLE
[FR] macrotrends.net data availability in OpenBB

### ISSUE THREAD

**Issue by mger1608** [OpenBB-finance/OpenBB#7121]
**What's the problem of not having this feature?**
The default option for macro and country level economic data comes from econDB, most likely because of econDB data fidelity and collaboration. EconDB also requires a $16/month or $167/annual subscription for their data. 

Macrotrends.net provides similar data to EconDB for free, which appears to be subsidized by their advertisements on the website. Macrotrends does not have documentation and it is difficult to validate its data sources. 

**Describe the solution you would like**
It would be great to be able to leverage data available from Macrotrends.net in the Country level economic dashboards in OpenBB. 

**Describe alternatives you've considered**
N/A

**Additional information**
N/A

**Comment by deeleeramone** [comment]
> Macrotrends.net provides similar data to EconDB for free, which appears to be subsidized by their advertisements on the website. Macrotrends does not have documentation and it is difficult to validate its data sources.
> 
> **Describe the solution you would like** It would be great to be able to leverage data available from Macrotrends.net in the Country level economic dashboards in OpenBB.
> 

The EconDB stuff should actually be fine without adding an API key, try it out!

The data on Macrotrends.net appears to be reprints of data that is published to FRED, without parameters and transformations, and is available already from several sources, such as: 

- `openbb-fred`
- `openbb-bls`
- `openbb-us-eia`
- `openbb-imf`
- `openbb-oecd`

FRED provides a wrapper for some OECD, IMF, BIS, ECB datasets.

Macro data should just come directly from the source, wherever possible.

**Comment by mger1608** [comment]
Interesting. Nothing from the EconDB widget will load for me but I attributed that to my not having an EconDB API key because I do not pay for subscription. 

Maybe I misinterpreted EconDB’s website about what is and is not available without a subscription.

**Comment by deeleeramone** [comment]
> Interesting. Nothing from the EconDB widget will load for me but I attributed that to my not having an EconDB API key because I do not pay for subscription.

Are there any error messages associated with things not loading? From the backend server console, or the browser console?

As of right now, at least where I am, it appears to be working as expected.

Top widget is from the Platform API endpoint (no API key set at all), `/api/v1/economy/country_profile`, bottom widget is from the built-in widget.

![Image](https://github.com/user-attachments/assets/5af62eee-26e3-4a14-bf17-182164adfb68)

**Comment by mger1608** [comment]
**Working widgets:**
- Country Indicators
- Economic Overview
- Upcoming Economic Events

**Non-working widgets:** 
- Economic Indicators
- Yield Curve

Browser Console: 

> Access to XMLHttpRequest at 'https://sdk.openbb.co/api/v1/economy/indicators?provider=econdb&symbol=RGDP&country=US&start_date=2021-01-01&frequency=quarter&transform=tpop' from origin 'https://pro.openbb.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> Access to XMLHttpRequest at 'https://sdk.openbb.co/api/v1/fixedincome/government/yield_curve?provider=econdb&limit=1000&symbol=US&sort=asc&country=united_states&date=2025-05-19' from origin 'https://pro.openbb.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> Access to XMLHttpRequest at 'https://sdk.openbb.co/api/v1/economy/indicators?provider=econdb&symbol=RGDP&country=US&start_date=2021-01-01&frequency=quarter&transform=tpop' from origin 'https://pro.openbb.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> Access to XMLHttpRequest at 'https://sdk.openbb.co/api/v1/fixedincome/government/yield_curve?provider=econdb&limit=1000&symbol=US&sort=asc&country=united_states&date=2025-05-19' from origin 'https://pro.openbb.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> Access to XMLHttpRequest at 'https://sdk.openbb.co/api/v1/economy/indicators?provider=econdb&symbol=RGDP&country=US&start_date=2021-01-01&frequency=quarter&transform=tpop' from origin 'https://pro.openbb.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> network-plugin.ts:300 
 GET https://sdk.openbb.co/api/v1/fixedincome/government/yield_curve?provider=econdb&limit=1000&symbol=US&sort=asc&country=united_states&date=2025-05-19 net::ERR_FAILED 400 (Bad Request)

> Access to XMLHttpRequest at 'https://sdk.openbb.co/api/v1/economy/indicators?provider=econdb&symbol=RGDP&country=US&start_date=2021-01-01&frequency=quarter&transform=tpop' from origin 'https://pro.openbb.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.Understand this error
network-plugin.ts:300 
            
            
> GET https://sdk.openbb.co/api/v1/economy/indicators?provider=econdb&symbol=RGDP&country=US&start_date=2021-01-01&frequency=quarter&transform=tpop net::ERR_FAILED 400 (Bad Request)

> Access to XMLHttpRequest at 'https://sdk.openbb.co/api/v1/fixedincome/government/yield_curve?provider=econdb&limit=1000&symbol=US&sort=asc&country=united_states&date=2025-05-19' from origin 'https://pro.openbb.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

![Image](https://github.com/user-attachments/assets/ab85ba7f-7c9f-4369-998a-a7a3ce6ab241)

**Comment by deeleeramone** [comment]
Ok, those are issues with the built-in widgets. But if you go via the self-hosted ones, they should be working fine.

![Image](https://github.com/user-attachments/assets/07c34743-5c34-493a-abf2-5184b2d17021)

**Comment by mger1608** [comment]
Ok, if I understand correctly then I should try to create my own endpoint from the free tier of EconDB and bring that into OpenBB vai the "Add data" protocol? Apologies if that's elementary, I have not attempted to bring my own data into the platform yet and want to make sure I have the terminology correct.

![Image](https://github.com/user-attachments/assets/fc144a35-80fe-46c4-8231-728ccab76d80)

**Comment by deeleeramone** [comment]
> Ok, if I understand correctly then I should try to create my own endpoint from the free tier of EconDB and bring that into OpenBB vai the "Add data" protocol? Apologies if that's elementary, I have not attempted to bring my own data into the platform yet and want to make sure I have the terminology correct.

No, you just start the API and add it as a backend. In the instructions [here](https://docs.openbb.co/workspace/platform-installer), you would skip installing - because you would already have the library/packages installed (that's what this repository is).

**Comment by mger1608** [comment]
That makes sense, I'm wondering if I need to try uninstalling and redownloading the install package. Can't seem to access the openbb CLI and cannot run the ' openbb-api' file per the instruction video @2:02 mark from the link you sent.

![Image](https://github.com/user-attachments/assets/7981e066-403b-4159-9e56-85f8fa7c099e)
![Image](https://github.com/user-attachments/assets/59df49db-1f67-4b55-a912-1ba0d5320cf3)

**Comment by mger1608** [comment]
@deeleeramone I tried uninstalling and deleting all OpenBB related files on my device and installing again fresh. I still get the same errors as the above screenshot.

If I try to run the open the file direct

![Image](https://github.com/user-attachments/assets/ea1a8490-3f9b-44fe-8aa8-8eeb06a462a8)

ly from CLI I get

**Comment by deeleeramone** [comment]
> [@deeleeramone](https://github.com/deeleeramone) I tried uninstalling and deleting all OpenBB related files on my device and installing again fresh. I still get the same errors as the above screenshot.

Not sure why an uninstallation would be necessary to just start the API, but yes, you cannot activate an environment, or run a shortcut, that you deleted the contents of.

Uninstall, delete the folder, and reinstall.

Or, install as a regular Python package - https://docs.openbb.co/platform/installation

**Comment by btheard3** [comment]
Hi! I’d love to work on this issue as my first OpenBB contribution.

I plan to explore macrotrends.net for free economic data sources, parse them using BeautifulSoup, and integrate them into OpenBB’s country-level economic dashboards.

Let me know if anyone else is working on this — otherwise I’ll start investigating and open a draft PR soon. Thanks!
